# Generated by Django 5.2 on 2025-12-01 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указано', max_length=255, unique=True, verbose_name='Наименование общественного транспорта')),
            ],
            options={
                'verbose_name': 'Тип общественного транспорта',
                'verbose_name_plural': 'Типы общественного транспорта',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указано', max_length=255, unique=True, verbose_name='Наименование транспорта')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Тип транспорта',
                'verbose_name_plural': 'Типы транспорта',
            },
        ),
        migrations.CreateModel(
            name='Measuring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_photo', models.ImageField(null=True, upload_to='photos', verbose_name='Изображение')),
                ('road_width', models.FloatField(null=True, verbose_name='Ширина проезжей части в м')),
                ('latitude_position', models.FloatField(null=True, verbose_name='Широта позиции замеряющего')),
                ('longtiude_position', models.FloatField(null=True, verbose_name='Долгота позиции замеряющего')),
                ('measurment_time', models.DateTimeField(verbose_name='Время замера')),
                ('measurment_duration', models.FloatField(null=True, verbose_name='Продолжительность измерения (мин)')),
                ('street_name', models.CharField(default='Не указано', max_length=255, verbose_name='Наименование улицы')),
                ('is_deleated', models.BooleanField(default=False, null=True, verbose_name='Замеряющий запросил удаление')),
                ('latitude_start', models.FloatField(null=True, verbose_name='Широта начала участка')),
                ('longtiude_start', models.FloatField(null=True, verbose_name='Долгота начала участка')),
                ('latitude_end', models.FloatField(null=True, verbose_name='Широта конца участка')),
                ('longtiude_end', models.FloatField(null=True, verbose_name='Долгота конца участка')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Комментарий')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор измерения')),
            ],
            options={
                'verbose_name': 'Измерение',
                'verbose_name_plural': 'Измерения',
            },
        ),
        migrations.CreateModel(
            name='PeopleInPublicTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitting_place', models.FloatField(verbose_name='Количество сидячих мест в транспорте')),
                ('standing_place', models.FloatField(verbose_name='Количество стоячих мест в транспорте')),
                ('entering_people', models.IntegerField(verbose_name='Количество вошедших в транспорт людей')),
                ('leaving_people', models.IntegerField(verbose_name='Количество вышедших из транспорта людей')),
                ('time', models.DateTimeField(verbose_name='Время прибытия транспорта')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Комментарий')),
                ('transport_number', models.CharField(max_length=10, verbose_name='Номер транспорта')),
                ('measuring', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data.measuring', verbose_name='Замер')),
                ('public_transport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data.publictransport', verbose_name='Тип общественного транспорта')),
            ],
            options={
                'verbose_name': 'Количество людей в общественном транспорте',
                'verbose_name_plural': 'Количество людей в общественном транспорте',
            },
        ),
        migrations.CreateModel(
            name='Intensivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanity', models.IntegerField(verbose_name='Количество')),
                ('measuring', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data.measuring', verbose_name='Замер')),
                ('transport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data.transport', verbose_name='Тип транспорта')),
            ],
            options={
                'verbose_name': 'Интенсивность',
                'verbose_name_plural': 'Интенсивности',
            },
        ),
    ]
