# Generated by Django 5.2 on 2025-04-15 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указано', max_length=255, unique=True, verbose_name='Наименование общественного транспорта')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указано', max_length=255, unique=True, verbose_name='Наименование транспорта')),
            ],
        ),
        migrations.CreateModel(
            name='Measuring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_photo', models.ImageField(null=True, upload_to='photos', verbose_name='Изображение')),
                ('road_width', models.FloatField(null=True, verbose_name='Ширина проезжей части в м')),
                ('latitude', models.FloatField(null=True, verbose_name='Широта')),
                ('longtiude', models.FloatField(null=True, verbose_name='Долгота')),
                ('measurment_time', models.DateTimeField(verbose_name='Время замера')),
                ('measurment_duration', models.FloatField(null=True, verbose_name='Продолжительность измерения (мин)')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор измерения')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleInPublicTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitting_place', models.IntegerField(verbose_name='Количество сидячих мест в траспорте')),
                ('standing_place', models.IntegerField(verbose_name='Количество стоячих мест в траспорте')),
                ('entering_people', models.IntegerField(verbose_name='Количество вошедших из траспорта людей')),
                ('leaving_people', models.IntegerField(verbose_name='Количество вышедших из траспорта людей')),
                ('time', models.DateTimeField(verbose_name='Время прибытия транспорта')),
                ('measuring', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data.measuring', verbose_name='Замер')),
                ('public_transport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data.publictransport', verbose_name='Тип общественного транспорта')),
            ],
        ),
        migrations.CreateModel(
            name='PublicTransportNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='Не указано', max_length=4, unique=True, verbose_name='Номер общественного транспорта')),
                ('public_transport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data.publictransport', verbose_name='Тип общественного транспорта')),
            ],
        ),
        migrations.CreateModel(
            name='intensivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanity', models.IntegerField(verbose_name='Количество')),
                ('measuring', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data.measuring', verbose_name='Замер')),
                ('transport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data.transport', verbose_name='Тип транспорта')),
            ],
        ),
    ]
