# Generated by Django 5.2 on 2025-04-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intensivity',
            options={'verbose_name': 'Интенсивность', 'verbose_name_plural': 'Интенсивности'},
        ),
        migrations.AlterModelOptions(
            name='measuring',
            options={'verbose_name': 'Измерение', 'verbose_name_plural': 'Измерения'},
        ),
        migrations.AlterModelOptions(
            name='peopleinpublictransport',
            options={'verbose_name': 'Количество людей в общественном транспорте', 'verbose_name_plural': 'Количество людей в общественном транспорте'},
        ),
        migrations.AlterModelOptions(
            name='publictransport',
            options={'verbose_name': 'Тип общественного транспорта', 'verbose_name_plural': 'Типы общественного транспорта'},
        ),
        migrations.AlterModelOptions(
            name='publictransportnumber',
            options={'verbose_name': 'Номер общественного транспорта', 'verbose_name_plural': 'Номера общественного транспорта'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'Тип транспорта', 'verbose_name_plural': 'Типы транспорта'},
        ),
    ]
