# Generated by Django 5.2 on 2025-04-15 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_alter_intensivity_options_alter_measuring_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peopleinpublictransport',
            name='public_transport',
        ),
        migrations.AddField(
            model_name='peopleinpublictransport',
            name='public_transport_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data.publictransportnumber', verbose_name='Номер общественного транспорта'),
        ),
    ]
