# Generated by Django 5.2 on 2025-04-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_remove_peopleinpublictransport_public_transport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinpublictransport',
            name='sitting_place',
            field=models.FloatField(verbose_name='Количество сидячих мест в траспорте'),
        ),
        migrations.AlterField(
            model_name='peopleinpublictransport',
            name='standing_place',
            field=models.FloatField(verbose_name='Количество стоячих мест в траспорте'),
        ),
        migrations.AlterField(
            model_name='publictransportnumber',
            name='number',
            field=models.CharField(default='Не указано', max_length=4, verbose_name='Номер общественного транспорта'),
        ),
    ]
