# Generated by Django 5.2 on 2025-10-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0004_alter_peopleinpublictransport_sitting_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measuring',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='measuring',
            name='longtiude',
        ),
        migrations.AddField(
            model_name='measuring',
            name='is_deleated',
            field=models.BooleanField(default=False, null=True, verbose_name='Замеряющий запросил удаление'),
        ),
        migrations.AddField(
            model_name='measuring',
            name='latitude_end',
            field=models.FloatField(null=True, verbose_name='Широта  конца участка'),
        ),
        migrations.AddField(
            model_name='measuring',
            name='latitude_position',
            field=models.FloatField(null=True, verbose_name='Широта позиции замеряющего'),
        ),
        migrations.AddField(
            model_name='measuring',
            name='latitude_start',
            field=models.FloatField(null=True, verbose_name='Широта начала участка'),
        ),
        migrations.AddField(
            model_name='measuring',
            name='longtiude_end',
            field=models.FloatField(null=True, verbose_name='Долгота конца участка'),
        ),
        migrations.AddField(
            model_name='measuring',
            name='longtiude_position',
            field=models.FloatField(null=True, verbose_name='Долгота позиции замеряющего'),
        ),
        migrations.AddField(
            model_name='measuring',
            name='longtiude_start',
            field=models.FloatField(null=True, verbose_name='Долгота  начала участка'),
        ),
        migrations.AddField(
            model_name='measuring',
            name='street_name',
            field=models.CharField(default='Не указано', max_length=255, verbose_name='Наименование улицы'),
        ),
    ]
