# Generated by Django 5.2 on 2025-11-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0005_remove_measuring_latitude_remove_measuring_longtiude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес'),
        ),
    ]
