# Generated by Django 5.2 on 2025-11-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0006_transport_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuring',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Комментарий'),
        ),
    ]
